{
 "title": "Service Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS All Statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[30s])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pgx Read Pool Acquired Conns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "pgxpool_read_acquired_conns", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pgx Write Pool Acquired Conns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "pgxpool_write_acquired_conns", "legendFormat": "__auto" }
   ]
  }
 ]
}